version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  
