version: 2
updates:
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
  - dependency-name: kramdown
    versions:
    - 2.3.0
