version: 2
updates:
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        patterns:
          - "*"
